### ISSUE TITLE
[bug] Mp3 file issues.

### ISSUE THREAD

**Issue by stephanie00100** [jonaaa20/AthamePlugin.Deezer#3]
Mp3 Diags results.

ID3V2 tag has an APIC frame (which is used to store images), but the image couldn’t be loaded.

Unsupported text encoding for APIC frame in ID3V2 tag.

No normalization undo information found. The song is probably not normalized by MP3Gain or a similar program. As a result, it may sound too loud or too quiet when compared to songs from other albums.

**Comment by FatKiwi** [comment]
Can you provide example URL? MP3 seems fine here.

**Comment by jonaaa20** [comment]
The issue comes from athame, not the plugin, you should open a issue on his repo.
