### ISSUE TITLE
the download flac stays in the middle and gives me an error

### ISSUE THREAD

**Issue by fabriccioguzman** [jonaaa20/AthamePlugin.Deezer#4]
[log20180103.log](https://github.com/jonaaa20/AthamePlugin.Deezer/files/1602359/log20180103.log)
http://www.deezer.com/es/track/69338541
I can reproduce it: yes
use the most recent version: yes
  this error happens because of my slow connection

**Comment by fabriccioguzman** [comment]
this error happens because of my slow connection

**Comment by jonaaa20** [comment]
Hmm... No problems here. But I'll check here.

**Comment by fabriccioguzman** [comment]
@jonaaa20 OK thanks, Before, this did not happen to me with the first version that released triple frecuency that downloaded well with slow connection, but since the 3 release this error happens to me But take it easy, do not rush and I appreciate your great effort :)

**Comment by jonaaa20** [comment]
Sorry but i can't do anything related to it, You better fix your internet.
